### ISSUE TITLE
Question: Why cri-o instead of cri-containerd?

### ISSUE THREAD

**Issue by hgfischer** [kinvolk/kubernetes-the-hard-way-vagrant#12]
Hello,

I am curious why you decided to use cri-o instead of cri-containerd. Could you please elaborate?

thanks!

**Comment by schu** [comment]
KTHW was using CRI-O up until [not so long ago](https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/ede3437ee84f9c0f54f2785b71c5d5aa09e36a9b) and I had no particular reason to switch. At the same time I like the idea of CRI-O being a lightweight CRI interface only (with the goal to "do one thing well").

**Comment by hgfischer** [comment]
Ok! Thanks for the clarification!
