### ISSUE TITLE
DNS verification step with busybox potentially failing with "latest"

### ISSUE THREAD

**Issue by asksven** [kinvolk/kubernetes-the-hard-way-vagrant#19]
Kudos for the repo, it helped me a lot "translating" KTWH from GCP to virtualbox.

I have spend the last 2 days (learning tons while) trying to find-out why the DNS resolution was failing until I found this:
https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/384/commits/f8f267e81d88753f5d5e68a962c9ddb40a8294f7

so I'd recommend being explicit about the version (as the kubernetes doc is here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) of busybox to use for testing `nslookup`:
`kubectl run busybox --image=busybox:1.28.4 --command -- sleep 3600`

If you prefer I can issue a PR for README.md and update a few other things like bumbing the k8s version number from `kubectl get nodes` to v1.11.2

**Comment by surajssd** [comment]
@asksven send PR yes they are always welcome :-)

**Comment by stefanlasiewski** [comment]
@surajssd I made a PR. Can you take a look?
